### ISSUE TITLE
Why not connecting PCM pins?

### ISSUE THREAD

**Issue by X-Ryl669** [QuickSpot/walter-hardware#1]
Looking at the schematic, I'm seeing that you're not connecting the PCM pins. That's a shame, since being able to place a call and answer it would be very useful too. Since ESP32 support I2S (I haven't checked the PCM format is the same), this would have been possible and very compact.

Can you explain your decision and if you can change that?

**Comment by daanpape** [comment]
Hi,

At this point in time we cannot do any hardware changes because the board is currently in the process of being certified by the accredited laboratory. We are currently also not aware of audio being available in the standardized and certified GM02SP firmware. This led to the decision to keep the ESP32 I/O pins free for the user's application.

Kind regards,
Daan
